# Generated by Django 2.1.3 on 2018-11-15 08:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0002_auto_20181115_0812'),
    ]

    operations = [
        migrations.AddField(
            model_name='ingredientprice',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='food.Source', verbose_name='source'),
        ),
    ]
