# Generated by Django 2.1.3 on 2018-11-15 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0003_ingredientprice_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='latitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
        migrations.AlterField(
            model_name='source',
            name='longitude',
            field=models.DecimalField(decimal_places=8, max_digits=12),
        ),
    ]
